export const words1 = [
  { id: 1, zh: "阿姨", pinyin: "āyí", ko: "이모, 아주머니" },
  { id: 2, zh: "爱好", pinyin: "àihào", ko: "취미" },
  { id: 3, zh: "办法", pinyin: "bànfǎ", ko: "방법" },
  { id: 4, zh: "办公室", pinyin: "bàngōngshì", ko: "사무실" },
  { id: 5, zh: "比赛", pinyin: "bǐsài", ko: "경기, 시합" },
  { id: 6, zh: "笔记本", pinyin: "bǐjìběn", ko: "노트북, 공책" },
  { id: 7, zh: "菜单", pinyin: "càidān", ko: "메뉴" },
  { id: 8, zh: "草", pinyin: "cǎo", ko: "풀" },
  { id: 9, zh: "超市", pinyin: "chāoshì", ko: "마트, 슈퍼마켓" },
  { id: 10, zh: "成绩", pinyin: "chéngjì", ko: "성적" },
  { id: 11, zh: "城市", pinyin: "chéngshì", ko: "도시" },
  { id: 12, zh: "词典", pinyin: "cídiǎn", ko: "사전" },
  { id: 13, zh: "蛋糕", pinyin: "dàngāo", ko: "케이크" },
  { id: 14, zh: "地方", pinyin: "dìfang", ko: "장소" },
  { id: 15, zh: "地铁", pinyin: "dìtiě", ko: "지하철" },
  { id: 16, zh: "地图", pinyin: "dìtú", ko: "지도" },
  { id: 17, zh: "电梯", pinyin: "diàntī", ko: "엘리베이터" },
  { id: 18, zh: "东", pinyin: "dōng", ko: "동쪽" },
  { id: 19, zh: "动物", pinyin: "dòngwù", ko: "동물" },
  { id: 20, zh: "耳朵", pinyin: "ěrduo", ko: "귀" },
  { id: 21, zh: "附近", pinyin: "fùjìn", ko: "근처" },
  { id: 22, zh: "刚才", pinyin: "gāngcái", ko: "방금" },
  { id: 23, zh: "个子", pinyin: "gèzi", ko: "키, 체격" },
  { id: 24, zh: "公园", pinyin: "gōngyuán", ko: "공원" },
  { id: 25, zh: "故事", pinyin: "gùshi", ko: "이야기" },
  { id: 26, zh: "关系", pinyin: "guānxi", ko: "관계" },
  { id: 27, zh: "国家", pinyin: "guójiā", ko: "국가" },
  { id: 28, zh: "黑板", pinyin: "hēibǎn", ko: "칠판" },
  { id: 29, zh: "后来", pinyin: "hòulái", ko: "나중에, 이후에" },
  { id: 30, zh: "护照", pinyin: "hùzhào", ko: "여권" },
];

export const words2 = [
  { id: 31, zh: "环境", pinyin: "huánjìng", ko: "환경" },
  { id: 32, zh: "黄河", pinyin: "Huáng Hé", ko: "황하" },
  { id: 33, zh: "会议", pinyin: "huìyì", ko: "회의" },
  { id: 34, zh: "机会", pinyin: "jīhuì", ko: "기회" },
  { id: 35, zh: "季节", pinyin: "jìjié", ko: "계절" },
  { id: 36, zh: "健康", pinyin: "jiànkāng", ko: "건강" },
  { id: 37, zh: "脚", pinyin: "jiǎo", ko: "발" },
  { id: 38, zh: "街道", pinyin: "jiēdào", ko: "거리" },
  { id: 39, zh: "节目", pinyin: "jiémù", ko: "프로그램" },
  { id: 40, zh: "节日", pinyin: "jiérì", ko: "명절" },
  { id: 41, zh: "经理", pinyin: "jīnglǐ", ko: "매니저" },
  { id: 42, zh: "句子", pinyin: "jùzi", ko: "문장" },
  { id: 43, zh: "客人", pinyin: "kèrén", ko: "손님" },
  { id: 44, zh: "空调", pinyin: "kōngtiáo", ko: "에어컨" },
  { id: 45, zh: "口", pinyin: "kǒu", ko: "입" },
  { id: 46, zh: "裤子", pinyin: "kùzi", ko: "바지" },
  { id: 47, zh: "筷子", pinyin: "kuàizi", ko: "젓가락" },
  { id: 48, zh: "礼物", pinyin: "lǐwù", ko: "선물" },
  { id: 49, zh: "历史", pinyin: "lìshǐ", ko: "역사" },
  { id: 50, zh: "脸", pinyin: "liǎn", ko: "얼굴" },
  { id: 51, zh: "邻居", pinyin: "línjū", ko: "이웃" },
  { id: 52, zh: "楼", pinyin: "lóu", ko: "층, 건물" },
  { id: 53, zh: "面包", pinyin: "miànbāo", ko: "빵" },
  { id: 54, zh: "奶奶", pinyin: "nǎinai", ko: "할머니" },
  { id: 55, zh: "南", pinyin: "nán", ko: "남쪽" },
  { id: 56, zh: "年级", pinyin: "niánjí", ko: "학년" },
  { id: 57, zh: "鸟", pinyin: "niǎo", ko: "새" },
  { id: 58, zh: "盘子", pinyin: "pánzi", ko: "접시" },
  { id: 59, zh: "啤酒", pinyin: "píjiǔ", ko: "맥주" },
  { id: 60, zh: "皮鞋", pinyin: "píxié", ko: "가죽신발" },
];

export const words3 = [
  { id: 61, zh: "瓶子", pinyin: "píngzi", ko: "병" },
  { id: 62, zh: "秋", pinyin: "qiū", ko: "가을" },
  { id: 63, zh: "裙子", pinyin: "qúnzi", ko: "치마" },
  { id: 64, zh: "声音", pinyin: "shēngyīn", ko: "소리" },
  { id: 65, zh: "世界", pinyin: "shìjiè", ko: "세계" },
  { id: 66, zh: "叔叔", pinyin: "shūshu", ko: "삼촌" },
  { id: 67, zh: "树", pinyin: "shù", ko: "나무" },
  { id: 68, zh: "数学", pinyin: "shùxué", ko: "수학" },
  { id: 69, zh: "水平", pinyin: "shuǐpíng", ko: "수준" },
  { id: 70, zh: "司机", pinyin: "sījī", ko: "기사" },
  { id: 71, zh: "太阳", pinyin: "tàiyáng", ko: "태양" },
  { id: 72, zh: "体育", pinyin: "tǐyù", ko: "체육" },
  { id: 73, zh: "同事", pinyin: "tóngshì", ko: "동료" },
  { id: 74, zh: "头发", pinyin: "tóufa", ko: "머리카락" },
  { id: 75, zh: "图书馆", pinyin: "túshūguǎn", ko: "도서관" },
  { id: 76, zh: "腿", pinyin: "tuǐ", ko: "다리" },
  { id: 77, zh: "文化", pinyin: "wénhuà", ko: "문화" },
  { id: 78, zh: "西", pinyin: "xī", ko: "서쪽" },
  { id: 79, zh: "习惯", pinyin: "xíguàn", ko: "습관" },
  { id: 80, zh: "洗手间", pinyin: "xǐshǒujiān", ko: "화장실" },
  { id: 81, zh: "先", pinyin: "xiān", ko: "먼저" },
  { id: 82, zh: "香蕉", pinyin: "xiāngjiāo", ko: "바나나" },
  { id: 83, zh: "校长", pinyin: "xiàozhǎng", ko: "교장" },
  { id: 84, zh: "新闻", pinyin: "xīnwén", ko: "뉴스" },
  { id: 85, zh: "信用卡", pinyin: "xìnyòngkǎ", ko: "신용카드" },
  { id: 86, zh: "行李箱", pinyin: "xínglǐxiāng", ko: "캐리어" },
  { id: 87, zh: "熊猫", pinyin: "xióngmāo", ko: "판다" },
  { id: 88, zh: "爷爷", pinyin: "yéye", ko: "할아버지" },
  { id: 89, zh: "以前", pinyin: "yǐqián", ko: "이전, 예전" },
  { id: 90, zh: "音乐", pinyin: "yīnyuè", ko: "음악" },
];
