export const Day9 = [
  { id: 1, zh: "旅游", pinyin: "lǚyóu", ko: ["여행하다"] },
  { id: 2, zh: "飞机", pinyin: "fēijī", ko: ["비행기", "항공기"] },
  { id: 3, zh: "机场", pinyin: "jīchǎng", ko: ["공항"] },
  { id: 4, zh: "宾馆", pinyin: "bīnguǎn", ko: ["(규모가 비교적 큰) 호텔"] },
  { id: 5, zh: "住", pinyin: "zhù", ko: ["숙박하다", "살다"] },
  { id: 6, zh: "想", pinyin: "xiǎng", ko: ["~하려고 하다", "생각하다"] },
  { id: 7, zh: "谢谢", pinyin: "xièxie", ko: ["고맙습니다", "감사합니다"] },
  { id: 8, zh: "不客气", pinyin: "bú kèqi", ko: ["별 말씀을요", "천만에요"] },
  { id: 9, zh: "对不起", pinyin: "duìbuqǐ", ko: ["죄송합니다", "미안합니다"] },
  { id: 10, zh: "没关系", pinyin: "méi guānxi", ko: ["괜찮다", "상관없다"] },
  { id: 11, zh: "帮助", pinyin: "bāngzhù", ko: ["돕다"] },

  { id: 12, zh: "问", pinyin: "wèn", ko: ["묻다", "질문하다"] },
  { id: 13, zh: "被", pinyin: "bèi", ko: ["~에게 ~을 당하다"] },
  { id: 14, zh: "护照", pinyin: "hùzhào", ko: ["여권"] },
  {
    id: 15,
    zh: "行李箱",
    pinyin: "xínglixiāng",
    ko: ["캐리어", "여행용 가방"],
  },
  { id: 16, zh: "带", pinyin: "dài", ko: ["가지다", "휴대하다", "데리다"] },
  {
    id: 17,
    zh: "跟",
    pinyin: "gēn",
    ko: ["~과", "따라가다", "뒤꿈치", "구두 굽"],
  },
  {
    id: 18,
    zh: "打算",
    pinyin: "dǎsuàn",
    ko: ["~할 계획이다", "~할 생각이다", "계획", "생각"],
  },
  { id: 19, zh: "其他", pinyin: "qítā", ko: ["다른 사람", "기타", "그 밖"] },
  { id: 20, zh: "起飞", pinyin: "qǐfēi", ko: ["이륙하다", "떠오르다"] },
  { id: 21, zh: "降落", pinyin: "jiàngluò", ko: ["착륙하다", "내려오다"] },
  { id: 22, zh: "旅行", pinyin: "lǚxíng", ko: ["여행하다"] },
  { id: 23, zh: "登机牌", pinyin: "dēngjīpái", ko: ["탑승권"] },
  { id: 24, zh: "赶", pinyin: "gǎn", ko: ["대다", "서두르다", "쫓다"] },
  { id: 25, zh: "航班", pinyin: "hángbān", ko: ["항공편", "운항편"] },
  { id: 26, zh: "签证", pinyin: "qiānzhèng", ko: ["비자"] },
  { id: 27, zh: "丢", pinyin: "diū", ko: ["잃어버리다", "잃다"] },
  { id: 28, zh: "规定", pinyin: "guīdìng", ko: ["규정하다", "규정", "규칙"] },
  {
    id: 29,
    zh: "乘坐",
    pinyin: "chéngzuò",
    ko: ["(자동차·배·비행기 등을) 타다"],
  },
  { id: 30, zh: "留", pinyin: "liú", ko: ["남기다", "남다", "머무르다"] },
  { id: 31, zh: "首都", pinyin: "shǒudū", ko: ["(한 나라의) 수도"] },

  { id: 32, zh: "顺利", pinyin: "shùnlì", ko: ["순조롭다"] },
  { id: 33, zh: "准时", pinyin: "zhǔnshí", ko: ["제때에", "시간에 맞다"] },
  { id: 34, zh: "推迟", pinyin: "tuīchí", ko: ["미루다", "연기하다"] },
  { id: 35, zh: "趟", pinyin: "tàng", ko: ["차례", "번"] },
  { id: 36, zh: "原因", pinyin: "yuányīn", ko: ["원인"] },
  { id: 37, zh: "许多", pinyin: "xǔduō", ko: ["매우 많다"] },
  { id: 38, zh: "既然", pinyin: "jìrán", ko: ["~인 이상", "~이 된 바에야"] },
  {
    id: 39,
    zh: "矿泉水",
    pinyin: "kuàngquánshuǐ",
    ko: ["생수", "미네랄 워터"],
  },
  { id: 40, zh: "轻", pinyin: "qīng", ko: ["가볍다"] },
];
