export const Day15 = [
  { id: 1, zh: "爱好", pinyin: "àihào", ko: ["취미"] },
  { id: 2, zh: "狗", pinyin: "gǒu", ko: ["개"] },
  { id: 3, zh: "猫", pinyin: "māo", ko: ["고양이"] },
  { id: 4, zh: "回", pinyin: "huí", ko: ["돌아오다", "돌아가다"] },
  { id: 5, zh: "唱歌", pinyin: "chànggē", ko: ["노래를 부르다"] },
  { id: 6, zh: "游泳", pinyin: "yóuyǒng", ko: ["수영", "수영하다"] },
  { id: 7, zh: "鱼", pinyin: "yú", ko: ["물고기", "생선"] },
  {
    id: 8,
    zh: "吧",
    pinyin: "ba",
    ko: ["문장 끝에 쓰여 청유·명령·추측을 나타냄"],
  },
  {
    id: 9,
    zh: "感兴趣",
    pinyin: "gǎn xìngqù",
    ko: ["관심이 있다", "흥미가 있다"],
  },
  { id: 10, zh: "画", pinyin: "huà", ko: ["(그림을) 그리다", "그림"] },
  { id: 11, zh: "游戏", pinyin: "yóuxì", ko: ["게임", "놀이"] },
  {
    id: 12,
    zh: "聊天(儿)",
    pinyin: "liáotiān(r)",
    ko: ["수다를 떨다", "잡담하다"],
  },
  { id: 13, zh: "爬山", pinyin: "páshān", ko: ["등산하다"] },
  { id: 14, zh: "饮料", pinyin: "yǐnliào", ko: ["음료"] },
  { id: 15, zh: "照片", pinyin: "zhàopiàn", ko: ["사진"] },
  { id: 16, zh: "照相机", pinyin: "zhàoxiàngjī", ko: ["사진기"] },
  { id: 17, zh: "多么", pinyin: "duōme", ko: ["얼마나"] },
  { id: 18, zh: "可爱", pinyin: "kě'ài", ko: ["귀엽다", "사랑스럽다"] },
  { id: 19, zh: "动物", pinyin: "dòngwù", ko: ["동물"] },
  { id: 20, zh: "只", pinyin: "zhī", ko: ["마리", "짝"] },
  { id: 21, zh: "马", pinyin: "mǎ", ko: ["말"] },
  { id: 22, zh: "鸟", pinyin: "niǎo", ko: ["새"] },
  { id: 23, zh: "老虎", pinyin: "lǎohǔ", ko: ["호랑이"] },
  { id: 24, zh: "然后", pinyin: "ránhòu", ko: ["그 다음에", "그런 후에"] },
  {
    id: 25,
    zh: "共同",
    pinyin: "gòngtóng",
    ko: ["공통의", "공동의", "함께", "다 같이"],
  },
  {
    id: 26,
    zh: "轻松",
    pinyin: "qīngsōng",
    ko: ["편안하다", "수월하다", "가뿐하다"],
  },
  { id: 27, zh: "计划", pinyin: "jìhuà", ko: ["~할 계획이다", "계획"] },
  { id: 28, zh: "往往", pinyin: "wǎngwǎng", ko: ["종종", "자주"] },
  {
    id: 29,
    zh: "随便",
    pinyin: "suíbiàn",
    ko: ["마음대로", "좋을 대로", "마음대로 하다"],
  },
  { id: 30, zh: "免费", pinyin: "miǎnfèi", ko: ["무료로 하다"] },
  { id: 31, zh: "举办", pinyin: "jǔbàn", ko: ["개최하다", "열다"] },
  { id: 32, zh: "邀请", pinyin: "yāoqǐng", ko: ["초대하다", "초청하다"] },
  { id: 33, zh: "聚会", pinyin: "jùhuì", ko: ["모임", "모이다"] },
  { id: 34, zh: "郊区", pinyin: "jiāoqū", ko: ["교외", "(도시의) 변두리"] },
  { id: 35, zh: "相同", pinyin: "xiāngtóng", ko: ["서로 같다", "똑같다"] },
  { id: 36, zh: "香", pinyin: "xiāng", ko: ["향기롭다", "(음식이) 맛있다"] },
  { id: 37, zh: "盒子", pinyin: "hézi", ko: ["상자"] },
  { id: 38, zh: "挺", pinyin: "tǐng", ko: ["꽤", "제법", "아주", "매우"] },
  { id: 39, zh: "海洋", pinyin: "hǎiyáng", ko: ["바다", "해양"] },
  {
    id: 40,
    zh: "不管",
    pinyin: "bùguǎn",
    ko: ["~하든지 간에", "~에 관계없이"],
  },
];
