export const Day14 = [
  { id: 1, zh: "运动", pinyin: "yùndòng", ko: ["운동하다", "운동"] },
  { id: 2, zh: "健康", pinyin: "jiànkāng", ko: ["건강하다"] },
  { id: 3, zh: "做", pinyin: "zuò", ko: ["하다", "만들다"] },
  {
    id: 4,
    zh: "会",
    pinyin: "huì",
    ko: ["~할 것이다", "(배워서) ~을 할 수 있다"],
  },
  {
    id: 5,
    zh: "在",
    pinyin: "zài",
    ko: ["~에 있다", "존재하다", "~에서", "~하고 있는 중이다"],
  },
  { id: 6, zh: "水", pinyin: "shuǐ", ko: ["물"] },
  { id: 7, zh: "跑步", pinyin: "pǎobù", ko: ["달리다", "뛰다"] },
  { id: 8, zh: "踢足球", pinyin: "tī zúqiú", ko: ["축구를 하다"] },
  { id: 9, zh: "打篮球", pinyin: "dǎ lánqiú", ko: ["농구를 하다"] },
  { id: 10, zh: "累", pinyin: "lèi", ko: ["피곤하다", "지치다"] },
  { id: 11, zh: "重要", pinyin: "zhòngyào", ko: ["중요하다"] },
  { id: 12, zh: "锻炼", pinyin: "duànliàn", ko: ["단련하다"] },
  { id: 13, zh: "起来", pinyin: "qǐlái", ko: ["일어서다", "일어나다"] },
  { id: 14, zh: "比赛", pinyin: "bǐsài", ko: ["경기", "시합"] },
  { id: 15, zh: "简单", pinyin: "jiǎndān", ko: ["간단하다", "단순하다"] },
  { id: 16, zh: "容易", pinyin: "róngyì", ko: ["쉽다"] },
  { id: 17, zh: "如果", pinyin: "rúguǒ", ko: ["만약"] },
  { id: 18, zh: "体育", pinyin: "tǐyù", ko: ["체육", "스포츠"] },
  { id: 19, zh: "瘦", pinyin: "shòu", ko: ["마르다", "여위다"] },
  { id: 20, zh: "减肥", pinyin: "jiǎnféi", ko: ["다이어트하다", "살을 빼다"] },
  { id: 21, zh: "散步", pinyin: "sànbù", ko: ["산책하다"] },
  { id: 22, zh: "压力", pinyin: "yālì", ko: ["스트레스", "부담"] },
  {
    id: 23,
    zh: "放松",
    pinyin: "fàngsōng",
    ko: ["(마음을) 편하게 하다", "긴장을 풀다"],
  },
  { id: 24, zh: "赢", pinyin: "yíng", ko: ["이기다"] },
  { id: 25, zh: "输", pinyin: "shū", ko: ["패하다", "지다"] },
  { id: 26, zh: "乒乓球", pinyin: "pīngpāngqiú", ko: ["탁구"] },
  { id: 27, zh: "网球", pinyin: "wǎngqiú", ko: ["테니스"] },
  { id: 28, zh: "羽毛球", pinyin: "yǔmáoqiú", ko: ["배드민턴"] },
  { id: 29, zh: "汗", pinyin: "hàn", ko: ["땀"] },
  { id: 30, zh: "力气", pinyin: "lìqi", ko: ["힘", "역량"] },
  {
    id: 31,
    zh: "棒",
    pinyin: "bàng",
    ko: ["대단하다", "(성적이) 좋다", "(수준이) 높다"],
  },
  { id: 32, zh: "好处", pinyin: "hǎochu", ko: ["이로운 점", "이익", "장점"] },
  { id: 33, zh: "进行", pinyin: "jìnxíng", ko: ["진행하다"] },
  { id: 34, zh: "报名", pinyin: "bàomíng", ko: ["신청하다", "등록하다"] },
  { id: 35, zh: "只要", pinyin: "zhǐyào", ko: ["~하기만 하면"] },
  { id: 36, zh: "正常", pinyin: "zhèngcháng", ko: ["정상이다", "정상적이다"] },
  { id: 37, zh: "躺", pinyin: "tǎng", ko: ["눕다", "드러눕다"] },
  { id: 38, zh: "梦", pinyin: "mèng", ko: ["꿈", "꿈을 꾸다"] },
  { id: 39, zh: "按时", pinyin: "ànshí", ko: ["제때에", "규정된 시간에 따라"] },
  { id: 40, zh: "缺少", pinyin: "quēshǎo", ko: ["부족하다", "모자라다"] },
];
